# SITE CONFIGURATION
title: Creaturae Blog # your site title
author: Creaturae # You :P
description: > # Meta description of Homepage
  Blog do website Creaturae.net. Artigos sobre tecnologia, desenvolvimento
  em geral.
baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://creaturae.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Creaturae Development
  links:
    - https://twitter.com/creaturae
    - https://www.facebook.com/creaturae
    - https://plus.google.com/+creaturae
    - https://github.com/creaturae

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Sobre', link: '/about'}
  - {name: 'Contato', link: '/contact'}

tagline: >
  Blog Creaturae. Artigos de tecnologia e programação.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: contact@creaturae.net # email for form submission

twitter_username: creaturae # replace with your_twitter_username or comment to remove link from footer
github_username:  creaturae # replace with your_github_username or comment to remove link from footer
instagram_username: creaturae # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: creaturae # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
